CREATE DATABASE TRIAGEM_COVID;
USE usuario;

CREATE TABLE USUARIO(
	USU_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	USU_NOME VARCHAR(50) UNIQUE INDEX,
	USU_MATRICULA VARCHAR(30) UNIQUE INDEX
);

CREATE TABLE PERGUNTA(
	PER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	PER_PERGUNTA VARCHAR(255)
);

CREATE TABLE TRIAGEM(
	TRI_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	TRI_USU_ID INTEGER,
	TRI_DATA TIMESTAMP,
	CONSTRAINT TRI_USU_FK FOREIGN KEY(TRI_USU_ID) REFERENCES USUARIO(USU_ID)
);

perguntaCREATE TABLE RESPOSTAS(
	RESP_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	RESP_TRI_ID INTEGER,
	RESP_PER_ID INTEGER,
	RESP_PERGUNTA VARCHAR(255),
	CONSTRAINT RESP_TRI_FK FOREIGN KEY(RESP_TRI_ID) REFERENCES TRIAGEM(TRI_ID),
	CONSTRAINT RESP_PER_FK FOREIGN KEY(RESP_PER_ID) REFERENCES PERGUNTA(PER_ID)
);
/*
CREATE TABLE RESPOSTAS(
	RESP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	RESP_PERGUNTA1 VARCHAR(255),
	RESP_PERGUNTA2 VARCHAR(255),
	RESP_PERGUNTA3 VARCHAR(255),
	RESP_PERGUNTA4 VARCHAR(255),
	RESP_PERGUNTA5 VARCHAR(255),
	RESP_PERGUNTA6 VARCHAR(255),
	RESP_PERGUNTA7 VARCHAR(255),
	RESP_PERGUNTA8 VARCHAR(255),
	RESP_PERGUNTA9 VARCHAR(255),
	RESP_PERGUNTA10 VARCHAR(255),
)
*/


